### ISSUE TITLE
svelte-add tailwindcss resets most markdown styles

### ISSUE THREAD

**Issue by wighawag** [svelte-add/svelte-add#115]
Hey svelte-add is a great way to get started

I noticed that when I combined `npx svelte-add tailwindcss` and  `npx svelte-add mdsvex ` the `example-markdown` page get no styling.

I guess this is because tailwind css reset. Would be great if msdvex template would get around this somehow ?

**Comment by manuel3108** [comment]
I personally don't agree with the above. If somebody decides to implement mdsvex and tailwindcss into his project, this is the expected behavior by default.

Svelte-adds main goal is to easily add different integrations to your new or existing svelte-add project. In the case mentioned above, this was done. If we would want to consider each incompatibility between each adder we would need to be extra carefull in the selection of the provided adders.
