### ISSUE TITLE
How to handle "community adders"? What about making this a monorepo?

### ISSUE THREAD

**Issue by manuel3108** [svelte-add/svelte-add#12]
This issue should discuss how we want to handle "community adders", so adders that are not made by the original author.

Example in this case is the [bulma adder](https://github.com/manuel3108/svelte-add-bulma).

As of the current layout of the project, there is the organization `svelte-add` which has all of it's adders in separate repositories.
@babichjacob proposed that if the adders match his quality standards he would be happy to add those to the org and give the initial authors write access to this special repo.

**What's the goal of this ticket?**
To discuss what should be the best way to handle all of this with at least overhead for the maintainer(s) as possible, while keeping usability for the users in mind

**My opinion**
I could imagine that community will create a bunch of those adders, as I think they are really helpful. Managing all those repositories the way @babichjacob proposed might cause a big overhead in my opinion.
Although normally i am against monorepos, I think that could make sense here. Let me explain:

Pros: 
* We only have on repo that needs to be maintained
* We don't need to manage user access for a bunch of different repos, everything could go with PR's
* Those adders could share some common code, if they have to (cannot image which code at the moment)
* We already have `svelte-add` which could handle the abstraction on top of `use preset` / `apply` ([use-preset docs for monorepos](https://usepreset.dev/docs/guides/hosting/))
* If Sveltekit is breaking something in the future, it would be easy to adapt all adders, because they are all in the same place

Cons:
* Well, monorepo
* Probably a bunch of issues will come together here

The list above is probably not complete, so feel free to add thinks

**Comment by babichjacob** [comment]
> @babichjacob proposed that if the adders match his quality standards he would be happy to add those to the org and give the initial authors write access to this special repo.

Yes! This is still what I want to do even after reading this issue.
 
> Although normally i am against monorepos, I think that could make sense here. Let me explain:
> 
> Pros:
> 
>     * We only have on repo that needs to be maintained

The existing repos have to be transferred into `svelte-add/svelte-adders` and all issues transferred (and links referencing them updated) and repositories archived, which is quite a bit of work. We also lose out on per-repository social preview images. SEO probably drops too.

>     * We don't need to manage user access for a bunch of different repos, everything could go with PR's

Reviewing every pull request would be dependent on me then. Alternatively, it would be hard to be willing to accept community adders if them being included means the author gets unfettered access to change all the other ones. 
 
>     * Those adders could share some common code, if they have to (cannot image which code at the moment)

Sharing code between presets isn't possible because, for security reasons, `apply` / `use-preset` runs presets without dependencies.

>     * We already have `svelte-add` which could handle the abstraction on top of `use preset` / `apply` ([use-preset docs for monorepos](https://usepreset.dev/docs/guides/hosting/))

True (once `svelte-add` works on Windows with `pnpx`). I also didn't know `use-preset` supported monorepos, so thanks for informing me!

>     * If Sveltekit is breaking something in the future, it would be easy to adapt all adders, because they are all in the same place

This doesn't make it easier or harder. The `svelte-add` organization page can already show the last update of each repository.

> 
> Cons:
> 
>     * Well, monorepo

As addressed above.

>     * Probably a bunch of issues will come together here

Issues being centralized would actually be a little easier to manage. On the other hand, stars being combined makes it hard to gauge the popularity of any particular adder so triaging issues / features for them becomes hard / impossible. 

---

So yeah, there's more reasons I'm against this than just inertia, although that is a huge factor. Thank you for writing this up and your interest in the project either way!

**Comment by manuel3108** [comment]
Thanks for you answer.
Fully understand your opinion now. Thanks for clarifying :smile:

**Comment by babichjacob** [comment]
We will move to a monorepo in the future, actually

**Comment by babichjacob** [comment]
It's the only maintainable way to make sure multiple adders, in fact, are composable.

It also means combined examples (e.x. Tailwind CSS typography getting included and set up if you select both `tailwindcss` and `mdsvex` https://github.com/svelte-add/mdsvex/issues/7) could be possible.

**Comment by bato3** [comment]
Btw, `apply` allows import modules https://github.com/preset/cli/pull/70

**Comment by babichjacob** [comment]
As mentioned before, **we are moving to a monorepo**. Here are some further reasonings why:

> > ```
> > * We don't need to manage user access for a bunch of different repos, everything could go with PR's
> > ```
> 
> Reviewing every pull request would be dependent on me then. Alternatively, it would be hard to be willing to accept community adders if them being included means the author gets unfettered access to change all the other ones.

I have since learned of [git submodules](https://github.blog/2016-02-01-working-with-submodules/) and CODEOWNERS so this is no longer a security nor maintenance issue.

 
> The existing repos have to be transferred into `svelte-add/svelte-adders` and all issues transferred (and links referencing them updated) and repositories archived, which is quite a bit of work. We also lose out on per-repository social preview images. SEO probably drops too.

With submodules, we don't have to do this anymore. (I still will transfer all the issues into `svelte-add` since it's really hard for everyone involved to deal with issues spread across multiple repositories).
 

> > ```
> > * Those adders could share some common code, if they have to (cannot image which code at the moment)
> > ```
> 
> Sharing code between presets isn't possible because, for security reasons, `apply` / `use-preset` runs presets without dependencies.

We are slowly saying goodbye to `apply` because this project has gotten too complex for it.


> > ```
> > * If Sveltekit is breaking something in the future, it would be easy to adapt all adders, because they are all in the same place
> > ```
> 
> This doesn't make it easier or harder. The `svelte-add` organization page can already show the last update of each repository.

Not sure what I was thinking with this response, since yes, having one codebase that contains all the adders' code indeed makes it dramatically easier to maintain them.

**Comment by manuel3108** [comment]
I think you have choosen the way to go here and decided how we should proceed in the future.
From my end, we could close here
