### ISSUE TITLE
Tailwind CSS: can't use multiple classes with @apply

### ISSUE THREAD

**Issue by brunobely** [svelte-add/svelte-add#158]
Similar to [this issue](https://github.com/sveltejs/language-tools/issues/484).

When using the tailwindcss adder and trying to set an apply at-rule like so:

```css
img {
  @apply inline max-w-sm;
}
```

`max-w-sm` is given a red underline and this error is shown:

```
semi-colon expectedcss(css-semicolonexpected)
```

**Comment by babichjacob** [comment]
This sounds like an IDE misconfiguration because this doesn't result in a build error.

There are steps here <https://github.com/sveltejs/language-tools/blob/75d635584a4b079e045f7cae446361e20352733a/docs/preprocessors/other-css-preprocessors.md> for addressing the concern, if it wasn't just a matter of making sure `lang="postcss"` was included on the `style` tag.
