### ISSUE TITLE
project initialization with svelte adders

### ISSUE THREAD

**Issue by manuel3108** [svelte-add/svelte-add#17]
This afternoon I had a though: How would it be, if we could immediately add some of those awesome adders while running `npm init svelte@next`

I found that this is quite an interesting question as this would help people setting up stuff really quickly. So there we are:
```
npm init svelte-extended
```
This command initializes a new sveltekit project, reads all available repos of this org, and gives the users the possibility to immediately install them. For who does not have a terminal at his hands, here is an image:
![image](https://user-images.githubusercontent.com/30698007/111529036-011aa400-8762-11eb-9945-90bba64fc524.png)

The repo for this stuff currently is here: https://github.com/manuel3108/create-svelte-extended (for anyone who wants to have a look). It's currently not tuned and probably has many problems. (Under the hood, this all just executes npm / npx commands)

What are your thoughts about that? Any ideas, problems etc?

PS: I'm writing this here, because it uses all the templates of this org. Depending on your thoughts and the problems you see, we could maybe also transfer this to this org.

**Comment by babichjacob** [comment]
I will absolutely explore this in the future!

What I'm expecting it to look like is
```sh
npm init @svelte-add/kit  # Create a SvelteKit project (their prompts) then launch the Svelte Adders selection menu 
# or
npm init @svelte-add/vite  # Create a Vite-powered Svelte app then launch the Svelte Adders selection menu 
```

**Comment by babichjacob** [comment]
Related: https://github.com/svelte-add/svelte-adders/issues/12

**Comment by babichjacob** [comment]
Closed by 09c11d5c5f9117eeca8fc5120943439a3b3e30c3. There may be some problems, so I'm leaving this issue open for a while.

**Comment by manuel3108** [comment]
@babichjacob I think you either referenced the wrong commute or wrote in the wrong issue, or I don't understand the commit ;)

**Comment by babichjacob** [comment]
> @babichjacob I think you either referenced the wrong commute or wrote in the wrong issue, or I don't understand the commit ;)


You're right, this is a better commit to look at:

https://github.com/svelte-add/svelte-add/commit/34876aaed8f90463c6c8475179719857e8e7adda#diff-956c9fec778dee35effe338392c21cd77daa31ca3391ae168d6d7d29efd6a0bdR252-R485

**Comment by babichjacob** [comment]
> Hey, just got some time to test it out. First of all, very well done!!! The process is smooth, the questions and selections are very clear and overall it "just works".

Thank you!!! I really appreciate you taking the time to check it out.


>     * First thing that i saw is that there is probably a problem while adding the demo files of the bulma adder (or at lease something other creating an issue to be displayed)

I still need to rewrite the Bulma adder. After making this project initializer tool, it is now at the top of the to-do list for [the big rewrite](https://github.com/orgs/svelte-add/projects/1).

>     * Its prompting me to `pnpm run dev -- --open  # start developing with a browser open` but apparently this command does not work at the moment. It gives the following error: ` ERROR   ERROR  Unknown option: 'open' For help, run: pnpm help run`

Please upgrade to the latest version of `pnpm` and let me know if that fixes it. I believe it was a recent change to align with how `npm` 7 works.


>     * In the message `Your TypeScript + mdsvex + ESLint + Prettier SvelteKit app is ready!` its somehow missing out the bulma part (+ scss eventually)

It deliberately doesn't mention Bulma and SCSS because they had error messages above. I can make it explicitly say "There was a problem setting up Bulma + SCSS (see above)." though.

>     * The generated site is a bit messed up
>       ![grafik](https://user-images.githubusercontent.com/30698007/132943909-90a774fa-5805-4e5b-a545-2629116b56d9.png)
>       Could have to do with the bulma demo files eventually

The current Bulma adder replaces the `__layout.svelte` file, removing the `app.(s)css` import. This will be solved by me rewriting it.

>     * It looks like its not asking for the which type of svelte-project we want to use (skeleton or demo). If thats the intendet way i would at least expect that it takes the skeleton app

Saying "Yes" to "Do you want example and demonstration code added to your app to demonstrate how to use the tools you've selected?" will choose the demo app. Saying "No. I am very familiar with the **application framework** and all the tools I've selected, so I fully understand how to use them without any guidance." will choose the skeleton template. This isn't entirely clear, but I'm also not sure how to make it more clear.

**Comment by manuel3108** [comment]
> Please upgrade to the latest version of pnpm and let me know if that fixes it. I believe it was a recent change to align with how npm 7 works.
Worked flawlessly now!

> It deliberately doesn't mention Bulma and SCSS because they had error messages above. I can make it explicitly say "There was a problem setting up Bulma + SCSS (see above)." though.
I think that would be good

> Saying "Yes" to "Do you want example and demonstration code added to your app to demonstrate how to use the tools you've selected?" will choose the demo app. Saying "No. I am very familiar with the application framework and all the tools I've selected, so I fully understand how to use them without any guidance." will choose the skeleton template. This isn't entirely clear, but I'm also not sure how to make it more clear.
Oh ok. I thought this question was primarly about adding the demos from the differnent adders, that we included a while ago.
I think it would be good to seperate the adder demos and the sveltkit-demo into two differnent questions

(I might find some time over this weekend to have a look at a few of this issues)

**Comment by babichjacob** [comment]
> I think it would be good to seperate the adder demos and the sveltkit-demo into two differnent questions

I personally don't know why they'd have different answers. When you select the demo app, you're not actually going to keep all the files it creates. It's mainly a *demonstration* (of course!) you look at rather than start your real app in. I like to advise people, in the Svelte Discord server, to select the demo app when they initialize a new SvelteKit project and look at it and what it does, then use the knowledge they gain from that in their real app (made from the skeleton template). You can have two folders / IDE windows for them in parallel to help.

Because adder demos are the same thing—adding new example files for demonstration and in some cases modifying existing ones—I think they should be part of the same question.

It is still the case that someone can initialize a SvelteKit app with `npm init svelte@next` or with `npm init @svelte-add/kit` and choose the skeleton template then use `npx svelte-add` to get adder demos later.

**Comment by manuel3108** [comment]
Yes, now that I understand your point, I agree. Also the question (from the cli) clearly describes what you were saying.

I'm going to close this right here, because your cli is up and running, and i have seen you rewriting a lot of adders the last days, so I would assume this is pretty much done.
