### ISSUE TITLE
[tailwind] can't use `@responsive` or `@layer components`

### ISSUE THREAD

**Issue by benmccann** [svelte-add/svelte-add#174]
My Tailwind 2 app had:

```
<style lang="postcss">
	@responsive {
		.intro-text-big {
			font-size: 5rem;
		}
	}
</style>
```

That broke when I upgraded to Tailwind 3. It also told me it was deprecated so I switched it to the new syntax which also doesn't work:

```
<style lang="postcss">
	@layer components {
		.intro-text-big {
			font-size: 5rem;
		}
	}
</style>
```

In both cases it can't seem to find the contents of `app.css`:
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

I need to copy that code into my `<style lang="postcss">` tag. In the past, that was always recommended against for performance reasons. I wonder how `npx svelte-add@latest tailwindcss` might be updated to allow for using `@responsive` or `@layer components`

**Comment by babichjacob** [comment]
Stylesheets are processed in isolation. This is thankfully well explained in Tailwind's [new documentation here](https://tailwindcss.com/docs/adding-custom-styles#layers-and-per-component-css). So unwrap that rule from `@layer components`.

Since the JIT engine—which is always active in Tailwind 3—generates variants for classes only when needed, directives like `@responsive` and `@variants` were removed. So unwrap that rule from `@responsive`.

**Comment by benmccann** [comment]
thanks for the pointer!!
