### ISSUE TITLE
Gracefully handle legacy adders that have not been rewritten, yet.

### ISSUE THREAD

**Issue by Leftium** [svelte-add/svelte-add#192]
Currently, the new svelte-add outputs a ERR_MODULE_NOT_FOUND error when run with a Preset-based adder like pug-adder. It is not obvious the true cause of the error is that svelte-add is not compatible with the adder:

https://github.com/Leftium/pug-adder/issues/1

This error could be made more understandable by detecting if the adder is based on Preset. If the adder is based on Preset, a friendly error message explaining the situation could be output. It might even suggest running the adder with Preset as a work-around like:

    npx @preset/cli apply Leftium/pug-adder

**Comment by babichjacob** [comment]
> This error could be made more understandable by detecting if the adder is based on Preset. If the adder is based on Preset, a friendly error message explaining the situation could be output. It might even suggest running the adder with Preset as a work-around like:

Oh, it's supposed to be the case that [`svelte-add` already detects presets](https://github.com/svelte-add/svelte-add/blob/c15d4eb7ee18abd0b0a3315a3e8584826cce5fa8/projects/svelte-add/index.js#L222) (because they have a `/` in them) and [runs the Preset CLI](https://github.com/svelte-add/svelte-add/blob/c15d4eb7ee18abd0b0a3315a3e8584826cce5fa8/projects/svelte-add/index.js#L758-L806). 

Let me look into this more later.

**Comment by manuel3108** [comment]
This seems to be working as expected right now
