### ISSUE TITLE
Creating a SvelteKit app is broken with recent changes to SvelteKit

### ISSUE THREAD

**Issue by d0x7** [svelte-add/svelte-add#206]
I just wanted to create a new svelte app with svelte-add, but when I typed ```npm run dev```, my browser tells me
```javascript
Error: %svelte.assets% in src/app.html should be replaced with %sveltekit.assets%
    at load_template (file:///var/v_www/spve-test/kit_ts_postcss_autoprefix_notemplate/node_modules/@sveltejs/kit/dist/cli.js:792:10)
    at file:///var/v_www/spve-test/kit_ts_postcss_autoprefix_notemplate/node_modules/@sveltejs/kit/dist/chunks/index.js:293:24
```

After googling around for an hour or so, I found what the cause was.

In sveltejs/kit#5016 a PR was merged that replaced  ```%svelte.X%```  with ```%sveltekit.X%```. 
That change has been reflected in kit/create-svelte, which svelte-add uses, so a simple re-build and push to npm should fix the issue.

**Comment by babichjacob** [comment]
I wasn't able to reproduce this (since `@svelte-add/create-kit` always uses the latest (well, `next` rather) version of `create-svelte`), but I've upgraded the lockfile with https://github.com/svelte-add/svelte-add/commit/9184304d627166c8f9cdf4472dce91177ab33b01#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR40 to try to eliminate the chance of it happening. Thanks!
