### ISSUE TITLE
How do you use svelte-add with Yarn?

### ISSUE THREAD

**Issue by mikwee** [svelte-add/svelte-add#215]
When I try `yarn svelte-add@latest tailwindcss`, Yarn can't find the command. If so, how *can* I call svelta-add from Yarn? Thank you.

**Comment by babichjacob** [comment]
I don't personally use Yarn, so please forgive me if I am mistaken:

It seems that [`yarn dlx`](https://yarnpkg.com/cli/dlx) is Yarn's equivalent of `npx`. That means the command you tried should look more like

```sh
yarn dlx svelte-add@latest tailwindcss
```
if that does in fact work, since [recentish Stack overflow answers allege that Yarn doesn't have an equivalent and that you just have to use `npx`.](https://stackoverflow.com/questions/66496166/is-there-any-yarn-equivalent-of-npx-preact-create#66612901)

**Comment by mikwee** [comment]
1. For some reason my Yarn does not support `yarn dlx`. The oddities of programming.
2. Honestly, what prevented me from using `npx` was the strong recommendation to not mix npm and Yarn together. Only now I've realized you can use `npx` specifically in a Yarn-centric project without much damage.

**Comment by manuel3108** [comment]
In that case, everything seems to be done here. Closing this now.
