### ISSUE TITLE
Add CoffeeScript

### ISSUE THREAD

**Issue by Leftium** [svelte-add/svelte-add#23]
**Repro steps:**

1. `npm init svelte@next`
2. Edit svelte.config.cjs so sveltePreprocess looks like this:
    `preprocess: sveltePreprocess({ coffeescript: { bare: true } }),`
3. `npx svelte-add postcss`
4. Inspect svelte.config.cjs:

![image](https://user-images.githubusercontent.com/381217/113604256-9e9f2000-960a-11eb-98d5-826d1b060c20.png)

Modifying sveltePreprocess() is a common, yet error-prone process. I think a robust method of adding/merging sveltePreprocess  into svelte.config.cjs is called for. Perhaps as a small NPM package?

Or perhaps instead of using sveltePreprocess() auto mode, the [stand-alone mode](https://github.com/sveltejs/svelte-preprocess/blob/main/docs/preprocessing.md#difference-between-the-auto-and-stand-alone-modes) should be used?

**Comment by babichjacob** [comment]
@Leftium are you prepared to transfer your `coffeescript-adder` repository to *me* so I can add it to the `svelte-add` organization (and rewrite it soon enough / eventually with the tools added in https://github.com/svelte-add/svelte-add/commit/82370e8d65c5deb5d1edd4a0e0a95b2ed0eeac95)?

**Comment by Leftium** [comment]
Sure, just let me know what I need to do

**Comment by babichjacob** [comment]
> Sure, just let me know what I need to do

Go to [the repository's settings](https://github.com/Leftium/coffeescript-adder/settings), select Transfer in the Danger Zone, enter my username `babichjacob` (not `svelte-add` because it doesn't let you transfer to an organization you don't belong to), and enter the repository name to confirm. 

<img width="774" alt="image" src="https://user-images.githubusercontent.com/22732095/123314002-0ffaba80-d4f8-11eb-8539-43902ab6fde7.png">

No more changes than that need to be made by you because references to `Leftium/coffeescript-adder` are automatically redirected to `svelte-add/coffeescript` by the transfer. (That means the adder should still work as it currently does until I rewrite it).

**Comment by babichjacob** [comment]
Then, on my side, I'll rename it from `coffeescript-adder` to `coffeescript` and add you as a collaborator / whatever gives you write access.

**Comment by babichjacob** [comment]
You've been sent an invitation to have Maintainer access to the repository. You don't need to do anything else, maybe ever again since it's such a simple adder, since the only thing left is for me to rewrite it.
