### ISSUE TITLE
Why `app.postcss` not `.css`

### ISSUE THREAD

**Issue by babakfp** [svelte-add/svelte-add#236]
Hi
Previously we were using `app.css` for TW stuff, but now it's called `app.postcss`. Is there a technical reason for this? Is it OK to rename it to `.css`?
Thanks for the tool agin🙏

**Comment by babichjacob** [comment]
It's been renamed to `app.postcss` since [the bug that prevented .postcss`, `.scss`, etc, from being used during SSR during dev](https://github.com/sveltejs/kit/pull/4882) has been fixed.

I think it makes sense to call it `app.postcss` because you can write PostCSS syntax there, which is more than CSS. I don't think it's the right idea to continue using `app.css` seeing as it's not a plain CSS file. This is a philosophical reason rather than a technical one, so yes you can continue using it as `app.css` if you want - it's your developer experience.

**Comment by babakfp** [comment]
Hey.
Thanks for the explanation.
Feel free to close the issue.
