### ISSUE TITLE
Append to, rather than overwrite files (such as $layout.svelte)

### ISSUE THREAD

**Issue by websocket98765** [svelte-add/svelte-add#24]
Is it possible to just add `import "./global.css"` to `$layout.svelte`, instead of overwriting it?  

Why?
I went through Svelte Kit docs & followed along. Then at the end, I ran `npx svelte-add tailwindcss --jit` in this project and thought it broke the site. Turns out the adder overwrote my `$layout.svelte`, instead of just adding `import "./global.css"` to it.

People might want to run the command at a later stage of their project.

**Comment by Leftium** [comment]
This is a work-around I use:
1. Make sure the git staging area is empty before running adders.
2. Run adders.
3. Look at diffs, and manually copy over my code that was deleted/undesirably modified by adders.

Perhaps this process could be documented before running adders for projects that have been modified from the scaffolding template. (And maybe add a warning if the git staging area is not empty.)

**Comment by babichjacob** [comment]
There are currently no areas I know of where `svelte-add` will overwrite an existing file rather than mutate it, and because it probably makes more sense for needed improvements on this to be identified by comments in the source code or by issues / pull requests depending on who finds them, I think it's time to close this issue as resolved.
