### ISSUE TITLE
Making a new adder

### ISSUE THREAD

**Issue by mattpilott** [svelte-add/svelte-add#246]
Hello,

I'd like to make an adder but am unsure how to actually develop one.

I can see from the other adders what files i need but how is it possible to run the adder locally as i develop?

Thanks!

**Comment by manuel3108** [comment]
Hey, sure! If you are still interested go ahead!

There is some information in the readme already: https://github.com/svelte-add/svelte-add#-developing-locally
And then, if you encounter any other questions, feel free to ask them here.

After your adder is set up and running, it get's a little tricky when including it into this repo structure, because we are currently making heavy use of git submodules.

**Comment by mattpilott** [comment]
Thanks, is svelte-add still in the process of being rewritten and if so should i hold off until that is done?

**Comment by manuel3108** [comment]
I'm not entirely sure if he has finished the rewrite 100%, because as you have seen he has not been really active on this repo recently. 

But looking at the code, it looks like most of the adders have been rewritten to the newer format. While starting just make sure that you are starting based of an rewritten adder. You could i.e. start with the bulma adder. But really any of the following adders highlighted in blue would serve as a starting point, as all of these have been rewritten.

![image](https://user-images.githubusercontent.com/30698007/231216117-6434cb77-dd24-4677-84de-a755bf7dfabd.png)

Some of the other adders also appear to be re-written, but I'm currently not really sure about their status.

**Comment by mattpilott** [comment]
ah ok thats helpful thanks, when i get some time ill have a go at making one

**Comment by manuel3108** [comment]
I will close this for now, but happy to further support here if necessary.
