### ISSUE TITLE
Add adder for Pico CSS.

### ISSUE THREAD

**Issue by Leftium** [svelte-add/svelte-add#253]
Adding [Pico CSS](https://picocss.com/) to SvelteKit is relatively simple, but the ideal method is not obvious. It involves adding an id to app.html and setting a SASS variable:

> Pico depends on `main`, `footer`, `header` being direct children of `body` for certain layouts, but that's not possible with sveltekit if you are doing it right.
> 
> However, pico has a `$semantic-root-element` variable that you can set as this element: `<div style="display: contents">%sveltekit.body%</div>`. So far this has fixed that for me but I haven't tried everything.
> 
> I did it like this.
> 
> ```
> 
> <div id="pico-root" style="display: contents">%sveltekit.body%</div>
> ```
> 
> ```css-scss
> // variables.scss
> $semantic-root-element: "div#pico-root"
> 
> // OR whever you import pico
> $semantic-root-element: "div#pico-root"
> @import '@picocss/pico/scss/pico';
> ```
source: https://github.com/picocss/pico/issues/201#issuecomment-1398004719

I think app.html could be left intact if the proper selector is used. Maybe something like:

    $semantic-root-element: "body div:first-child"

~~Do +layout.svelte files add extra layers of  `<div>` containers that would cause this method to break? (Only a small part of Pico CSS depends on the `semantic-root-element`; some vertical spacing between container elements.)~~

**Edit:**  Inspecting https://learn.svelte.dev/tutorial/layouts seems to confirm layouts don't add additional layers of `<div>` containers. (Although more complex custom layouts with CSS grid, flex, etc may result in breaking Pico's semantic root.)

**Comment by caio-bernardo** [comment]
Hello, Can I make this adder? I use PicoCSS + Svelte a lot, so it would be very helpful for me.

**Comment by caio-bernardo** [comment]
I think my adder is working correctly, can I make a pull request?

**Comment by manuel3108** [comment]
Hey!
Sure!

I would suggest that we create a separate repo for this adder, as it's done with nearly all adders currently: https://github.com/svelte-add. In example, the [tailwindcss](https://github.com/svelte-add/tailwindcss) adder is in its own repo, and then included here via git submodules. This is currently the way, because we want to get the SEO support, a new / separate repo provides.
The easiest way would be if you create a separate repo for [the picocss directory](https://github.com/caio-bernardo/svelte-add/tree/e1352f1c0625357d73552e43bf080dd800f0bdee/projects/svelte-add/adders/picocss) and then send a transfer request to my personal account @manuel3108. After that, I can move that repo into the org.

It would be great if you could also create a PR here, for the other two changes you made, so that I can combine everything in this repo.

**Comment by caio-bernardo** [comment]
Hello, I have made the pull request and send the transfer request, I think it's all done.

**Comment by manuel3108** [comment]
This was released with the latest update. Thanks for all your preparation work!
