### ISSUE TITLE
Adding full support for SASS

### ISSUE THREAD

**Issue by retr0cube** [svelte-add/svelte-add#303]
Hi!
I really admire the SASS syntax and how efficient it is to write, so I decided to clone/fork the SCSS adder and tweak it for SASS! (It's in svelte-add/sass PR #1)

I desperately need this adder to be implemented because there's no similar effort to bring SASS/SCSS support to Sveltekit (global styles and variables...)

**Comment by manuel3108** [comment]
Hey!

thanks for your contribution and thanks for mentioning the PR here, as I did not follow the other repos until now.
I'm absolutely not familiar with SASS, so I'll leave it up to you to determine if everything works as expected.

But, I can help you getting this merged!
In order to do that I have already merged your PR https://github.com/svelte-add/sass/pull/1 and created a new branch here with the updated submodule. You can find all of this in the PR: https://github.com/svelte-add/svelte-add/pull/304

As per the pipeline there appears to be a problem linting the changed files, see checks. You can execute the linting locally as per the [README](https://github.com/svelte-add/svelte-add#-developing-locally) the code looks fine although the [tests are not passing](https://github.com/svelte-add/svelte-add/actions/runs/5991146801/job/16249188492?pr=304).

The only thing I'm not sure of is that we have 24 results for `scss` in the `sass` folder. Again, im not familiar with sass, so this might be intendet:
![image](https://github.com/svelte-add/svelte-add/assets/30698007/5ecdfe2c-f5e2-4bda-a3b5-0d68fdf5af47)

**Comment by retr0cube** [comment]
> Hey!
> 
> thanks for your contribution and thanks for mentioning the PR here, as I did not follow the other repos until now. I'm absolutely not familiar with SASS, so I'll leave it up to you to determine if everything works as expected.
> 
> But, I can help you getting this merged! In order to do that I have already merged your PR [svelte-add/sass#1](https://github.com/svelte-add/sass/pull/1) and created a new branch here with the updated submodule. You can find all of this in the PR: #304
> 
> As per the pipeline there appears to be a problem linting the changed files, see checks. You can execute the linting locally as per the [README](https://github.com/svelte-add/svelte-add#-developing-locally) the code looks fine although the [tests are not passing](https://github.com/svelte-add/svelte-add/actions/runs/5991146801/job/16249188492?pr=304).
> 
> The only thing I'm not sure of is that we have 24 results for `scss` in the `sass` folder. Again, im not familiar with sass, so this might be intendet: ![image](https://user-images.githubusercontent.com/30698007/263530674-5ecdfe2c-f5e2-4bda-a3b5-0d68fdf5af47.png)

Hi!
I totally missed the _info.js file although I made sure to search for references of "scss" through the entire directory but it's fine I will fix it.

In regards to SCSS vs SASS, they're pretty much the same (except SASS uses indented syntax) and require the same `sass` package to function, so everything _should_ work smoothly!

**Comment by retr0cube** [comment]
@manuel3108 I should also mention that SASS isn't an option in the CLI quite yet, when should I expect that?

**Comment by manuel3108** [comment]
@retr0cube I couldn't release jet, as the tests are not passing

**Comment by retr0cube** [comment]
Oh ok!

**Comment by manuel3108** [comment]
@retr0cube Thanks so much for your help on this! Your last commit also fixed the tests! From there on, I only fixed the one formatting error mentioned above and update the submodules to reflect the changes.

The latest release now includes the sass-adder!

As you have completely rewritten the adder, I have invited you as a collaborator to the [svelte-add/sass](https://github.com/svelte-add/sass) repo, thanks so much!

**Comment by retr0cube** [comment]
> @retr0cube Thanks so much for your help on this! Your last commit also fixed the tests! From there on, I only fixed the one formatting error mentioned above and update the submodules to reflect the changes.
> 
> The latest release now includes the sass-adder!
> 
> As you have completely rewritten the adder, I have invited you as a collaborator to the [svelte-add/sass](https://github.com/svelte-add/sass) repo, thanks so much!

No problem, OSS is part of my heart; Although all I did is just clone the scss adder and tweak it for sass
