### ISSUE TITLE
Check support for svelte 5

### ISSUE THREAD

**Issue by manuel3108** [svelte-add/svelte-add#317]

**Comment by codepilotsf** [comment]
`npx svelte-add@latest tailwindcss` does not currently work with Svelte 5 – silently fails to install tailwindcss due to dependency issues (doesn't recognize svelte@5 as a valid dependency). But it does update your postcss config which fails to import tw because it failed to install. It's easily fixable with `npm install tailwindcss`. Would be nice if svelte-add could recognize svelte 5 as a valid dependency, though :-)

**Comment by manuel3108** [comment]
This is supported by `svelte-add`s successor [`svelte-compose`](https://svelte-compose.com/)
