### ISSUE TITLE
Adding content to app.html and static

### ISSUE THREAD

**Issue by Slyker** [svelte-add/svelte-add#320]
Hi,
I want to create a plugin for theming which will require to add static folder (with files) and insert a script tag inside app.html that import entry point of the theme manager.
What do you think sorry if I'm too noob for this.

**Comment by manuel3108** [comment]
I'm not 100% sure i understand exacly what you mean. 

You want to create a svelte-add adder that modifies the app.html file and files in the static folder? Do you have a link to the documentation of the theme manager, so that I can have a look if this would be feasible with the current implementation?

**Comment by Slyker** [comment]
Hey 
One codesandbox is better than 10 000 words so:
https://codesandbox.io/p/sandbox/29lj2s

It's still WIP and meant to be released open source

**Comment by manuel3108** [comment]
Hey @Slyker 

thanks for the codesandbox. I had a really breif look at it. 
Based on the changes you have made to the app.html and static folder, it looks like those change could also be made within the svelte components /routes / files. Currently I don't see any reasons, why you have it implemented the way it is. Maybee I'm overseeing something. 

But, thats outside the scope of this repository. 

As you might understand we are also not able to add every very small project to svelte-add, as we would have multiple thousands of implementations that would be really hard to maintain. Additionally, this repo is undergoing a maintainer change at the moment, that's why currently its more important to fix existing integrations instead of providing new ones.

Once your project is published to npm and has gained some tracktion, please feel free to reopen this issue.

Thanks!

**Comment by Slyker** [comment]
Hey
I had to make it in app.html so it's able to load theme before page loads (maybe there's a better way).
Anyway I just wanted to ask if this is compatible with svelte-add. I'll enhance my system and release it on npm if it's worthy.
Thanks !
