### ISSUE TITLE
`pkg-pr-new` not releasing all required packages

### ISSUE THREAD

**Issue by manuel3108** [svelte-add/svelte-add#419]
### Topic

ci

### Version

latest

### Expected behavior

See #416 

We only published the drizzle adder. But when you try to execute the adder with someting like this: 

```
pnpm dlx https://pkg.pr.new/svelte-add/svelte-add@416 --path ./temp
```

you will get this error:
```
 ERR_PNPM_FETCH_404  GET https://pkg.pr.new/svelte-add/svelte-add@416: Not Found - 404
```

### Actual behavior

See #403 

we should also publish all (internal) dependencies of the project, in order to make that specific example work

**Comment by AdrianGonz97** [comment]
Ah, it's cause `svelte-add` has the adders listed as `peerDependencies` instead of `dependencies` or `devDependencies`, which is what's checked here:
https://github.com/svelte-add/svelte-add/blob/7a1cb1ad800d9f30d4871dbfc6a2e679d3d3af5b/scripts/get-deps-to-publish.js#L46-L48

adding `dep.peerDepedencies?.[pkg.name]` to that condition should fix it right up!
