### ISSUE TITLE
core method to merge a template with project

### ISSUE THREAD

**Issue by benmccann** [svelte-add/svelte-add#445]
### Topic

@svelte-add/core

### Description

`create-svelte` works by copying template files into the user's project. Things like an `.eslintignore`, `.prettierrc`, etc. get copied over and just dropping them in this directory can be a little nicer than inserting their contents into a method in a `.js` file. It would be nice to port over the prettier, eslint, playwright, and vitest setup into this project and having that functionality be available would make it a lot easier

### Describe the solution you'd like

Some features it has:
- you can put `+typescript` or `-typescript` in the directory name if it should run only if you do or don't have typescript installed. It also works with any adder name, but I'm not sure that's necessarily required. Just being able to have a TypeScript and non-TypeScript version would be a great start that handles most of the cases
- you can put a `package.json` in that directory and it will be merged into the user's `package.json`
- you can put sub-directories like `src/lib/db` or `src/routes/login` and it will copy files over with that layout. this is less used that the other two, but can be a nice thing to have

**Comment by manuel3108** [comment]
I don't fully agree with this one yet. 

There is a few things that we need to keep in mind. `create-svelte` is intended to be a one-off command to kickof a project. Thus, you cannot execute `create-svelte` on an existing project, which is one of the reasons they come a away with having template files like in [`+eslint+prettier`](https://github.com/sveltejs/kit/tree/main/packages/create-svelte/shared/%2Beslint%2Bprettier), where they just assume that they can overwrite the `lint` command inside the `package.json` because it's been a new project, a nobody other than the cli should have been able to make modifications at this point.

Since our cli can be run even later on, it could already be the case that the user has already added a `lint` command, potentially with some completely unexpected tooling. That's why I don't think it will be safe enough to just merge files like the `package.json`. But I think that this would only apply for files that are modified quite frequently and do not belong to any tools we have adders for. That would mean that I think your idea could work perfectly for files like the `eslint.config.js`

For the mentioned `eslint.config.js` I could imagine having a file definition like this inside the adder definition
```js
{
    name: () => "eslint.config.js",
    contentType: "script",
    content: ({ typescript, fromTemplate }) => {
        fromTemplate(`eslint/${typescript.installed ? "+" : "-"}/eslint.config.js`);
    },
},
```

As for the `package.json` I think we could perfectly handle that with our current tooling without any additional work.

**Comment by benmccann** [comment]
The `package.json` part probably isn't the most important, but the merging is pretty minimal. Usually just `dependencies` and `devDependencies`. It's really just a nice shortcut for adding dependencies like this:

https://github.com/sveltejs/kit/blob/main/packages/create-svelte/shared/%2Bprettier/package.json

Although maybe there's concern about what to do if a user already has a different version of the package added. Should it update the always, only if newer, never? Although we'll have to answer that question either way if we have a utility method. But we could have multiple implementations of a utility method, which could be nice in forcing people to think about the behavior, but maybe we also want to have one that we recommend as the default?

**Comment by manuel3108** [comment]
As both adders we thought would require this have been implement, we can safely close this for now. If something arises in the future where this might help, we can just re-open this.
