### ISSUE TITLE
Script for adder generation.

### ISSUE THREAD

**Issue by rnbokade** [svelte-add/svelte-add#472]
### Topic

Base

### Description

To accelerate the development and for maintaining standards in boilerplate while adding new adders, can we create a CLI to that would be available only within the repository context, allowing us to add new adder package by a cli wizard, which asks name of adder, dependencies, options etc. within the wizard, resulting in quicker scaffolding of a new adder. This could greatly help speed up development of community adders, while maintaining the standards.

**Comment by manuel3108** [comment]
There is still a lot of work to do regarding automation and community adders. Community adders are planned, but are not even close to be implemented anytime soon, that's why documentation is lacking. 
I'm not sure if a cli is the correct way do this as it would generate maintenace overhead, but we should at least have appropriate templates once we get there!

**Comment by ieedan** [comment]
I am working on a package right now [template-factory](https://github.com/ieedan/template-factory-js) that could be useful for creating a CLI if that was the route you wanted to go. I think it would probably limit the overhead you are talking about if you wanted to have an internal CLI.

### How it would work
You could create a js/ts script in the root of the project. Add a script in package.json like `templates:create` or something.

You would have a `template` under the adders directory that you would reference from the script. 

You can run any other code or prompts to help make steps easier such as allowing them to pick a category or create a new one from the CLI.

Initially it could look something like this, this just prompts the user and copies the files to where they specify but you could add prompts and such to improve the workflow.
```ts
import { create } from 'template-factory';
import * as util from 'template-factory/util';

const main = async () => {
  await create({
    name: 'templates:create',
    version: '1.0.0',
    templates: [
      {
        name: 'custom-adder',
        // probably don't actually need the path resolver here
        path: util.relative('./adders/template', import.meta.url),
        flag: 'custom-adder',
        // you could add prompts down here to improve setup
      }
    ]
  })
}

main(); 
```

Let me know if this is something that makes and I can try and model it better in a PR! If not no worries.

**Comment by manuel3108** [comment]
Thanks for bringing this to my attention again, and thanks for putting in the hard work @ieedan.

Since this issue was raised we had some restructuring going, which made generating new adders much easier. See [this commit](https://github.com/svelte-add/svelte-add/commit/8fbdd22f8e9ab7bac79f9a1de03df4373396dd12). Therefore I don't think such a cli makes sense at this point, as this would cause more Maintenace overhead than actual benefit.

Closing this.
