### ISSUE TITLE
Storybook Package Manager

### ISSUE THREAD

**Issue by mckoda09** [svelte-add/svelte-add#554]
### Topic

cli

### Version

2.7.3

### Actual behavior

When installing Storybook, package manager is npm by default

**Comment by AdrianGonz97** [comment]
Is there an existing `package-lock.json` file in the project? If so, then that's the expected behavior. If you want to avoid installs, add the `--skip-install` flag.

If that's not the case, then we're going to need more information as I'm unable to reproduce this when installing storybook on a new project. Can you provide a reproduction project along with reproduction steps?

**Comment by mckoda09** [comment]
`pnpm create svelte && pnpx svelte-add && pnpm i`

**Comment by mckoda09** [comment]
ok, i have tried using bun, it works normally

**Comment by manuel3108** [comment]
You could also help `svelte-add` determine the correct package manager by running a `pnpm i` directly after create, like this:

```
pnpm create svelte && pnpm i && pnpx svelte-add && pnpm i
```
